---
fullnameOverride: argocd

server:  
  config:
    url: https://argocd.<<VAR_NGINX_DOMAIN>>
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: $google-oidc-secret:clientId
          clientSecret: $google-oidc-secret:clientSecret
        type: oidc
        id: google
        name: Google
