---
fullnameOverride: argocd

dex:
  envFrom:
    - secretRef:
        name: google-oidc-secret

server:  
  config:
    url: https://argocd.<<VAR_NGINX_DOMAIN>>
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: $GOOGLE_CLIENT_ID
          clientSecret: $GOOGLE_CLIENT_SECRET
        type: oidc
        id: google
        name: Google

#$google-oidc-secret:GOOGLE_CLIENT_ID        
#$google-oidc-secret:GOOGLE_CLIENT_SECRET