---
fullnameOverride: argocd

server:  
  config:
    url: https://argocd.<<VAR_NGINX_DOMAIN>>
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: aaasdfsdfsdfsdf
          clientSecret: test-client-secret
        type: oidc
        id: google
        name: Google

#$google-oidc-secret:GOOGLE_CLIENT_ID        
#$google-oidc-secret:GOOGLE_CLIENT_SECRET