---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:nap-devops/nap-devops-argocd-apps.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-genuine
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:nap-devops/nap-genuine-deployment.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-genuine-docs
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:nap-devops/nap-genuine-docs-deployment.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-vms
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:nap-devops/nap-vms-deployment.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-onix
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:wintech-thai/onix-argocd-apps.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-kaspa
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:kaspa-chain/kaspa-deployment.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-please-scan
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:wintech-thai/please-scan-argocd-apps.git
---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret-rtarf-ads
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:rtaf-soc/rtarf-ads-argocd-apps.git
