---
apiVersion: v1
kind: Secret
metadata:
  name: github-ssh-secret
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque    
data:
  sshPrivateKey: <<SSH_KEY_BASE64>>
stringData:
  url: git@github.com:rtaf-soc/rtaf-soc-argocd-apps.git
