apiVersion: v1
kind: Secret
metadata:
  name: local-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
    custom: "true"
type: Opaque
stringData:
  name: <<VAR_ENVIRONMENT>>
  server: https://notused
  config: ""
