apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-issuer-prod
  namespace: cert-manager
spec:
  acme:
    server: <<VAR_LETENCRYPT_SERVER>>
    preferredChain: "ISRG Root X1"
    email: pjame.fb@gmail.com
    privateKeySecretRef:
      name: lets-encrypt-issuer-prod-key # The operator will create this for us
    solvers:
    - dns01:
        cloudDNS:
          project: <<VAR_CLOUD_DNS_PROJECT>> # Change to your project here
          serviceAccountSecretRef:
            name: gcp-cloud-dns-account-key
            key: service-account.json
